[package]
name = "mutual_credit_clearing"
version = "0.1.0"
authors = ["vanarchist <v4narchist@gmail.com>"]
edition = "2018"

[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
hdk = { git = "https://github.com/holochain/holochain-rust", tag = "v0.0.23-alpha1" }
hdk-proc-macros = { git = "https://github.com/holochain/holochain-rust", tag = "v0.0.23-alpha1" }
holochain_wasm_utils = { git = "https://github.com/holochain/holochain-rust", tag = "v0.0.23-alpha1" }
holochain_json_derive = { version = "0.0.14" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
