[[dnas]]
id = "holochain-mutual-credit-clearing-dna"
file = "./dist/holochain-mutual-credit-clearing.dna.json"
hash = "QmDontCheck"

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcScjcgKqXC5pmfvka9DmtEJwVr548yd86UPtJGGoue9ynuikuRTN7oE5zcjgbi"
keystore_file = "./agent1.keystore"

[[instances]]
id = "instance1"
dna = "holochain-mutual-credit-clearing-dna"
agent = "test_agent1"
[instances.storage]
type = "memory"
path = "tmp-storage"

[[interfaces]]
id = "http-interface1"
[interfaces.driver]
type = "http"
port = 8888
[[interfaces.instances]]
id = "instance1"


